### ISSUE TITLE
Any sample about health checks for Sql?

### ISSUE THREAD

**Issue by phisain** [AppMetrics/Samples.V2#2]
Hello there, I'm searching for a sample of health checks for sql, also I found nothing about that in the documentation. Thanks in advance for your reply.

**Comment by alhardy** [comment]
Does this help? https://github.com/AppMetrics/Health/blob/dev/sandbox/HealthSandbox/Host.cs#L94

Yeah still need to add this to the documentation

**Comment by phisain** [comment]
Yes, it could help me, thanks a lot.
