### ISSUE TITLE
Is any sample of healthcheck with reporter (InfluxDb as example)?

### ISSUE THREAD

**Issue by igor-moskvitin** [AppMetrics/Samples.V2#3]
I found only this [article](https://al-hardy.blog/2017/04/28/asp-net-core-monitoring-with-influxdb-grafana/), but its for previous version of app-metrics. Samples from this repo using reporters with metrics only (not with health) or may i missed something?

**Comment by alhardy** [comment]
You are correct, support for reporting health status was removed in a later version of App Metrics. Originally Health functionality was included in the App Metrics package, Microsoft now have a similar Health implementation so I decided to decouple Health from Metrics but lost some functionality in the process.

This is on my [backlog](https://github.com/AppMetrics/Health/issues/9), although I am still thinking whether or not I should continue with App Metrics Health since Microsoft have implemented an equivalent.

**Comment by igor-moskvitin** [comment]
Its about [this](https://github.com/dotnet-architecture/HealthChecks)? If i right - it has only endpoints capability, but not own reporter and looks like abandoned...

**Comment by alhardy** [comment]
Yeah was referring to that. I think it was going to be released as part of aspnet core 2.0, now potentially 2.1.

No it doesn't have a reporter, but we could implement a custom extension to use App Metrics or similar to report the results.

It wouldn't take too long to implement the reporting functionality, I'm just cautious of wasting time. I guess if App Metrics Health provides additionality functionality over the Microsoft implementation App Metrics would still be used, but then I'm thinking the other option would be to provide extensions on the Microsoft implementation.

Will think a bit more about it.

**Comment by DanielMarcial** [comment]
We are considering AppMetrics for both metric collection and health monitoring of our decentralized UWP app (use case for kiosk mode terminals) so a reporting of health check information to a central server would make sense to us (it would also be an implicit heartbeat). Metric reporting appears to be already possible thanks to .NET Standard 2.0 (using AppMetricsTaskScheduler), but health reporting not (if I understand correctly). The console sample only supports writing to the console and no external reporting if I am correct.

Perhaps we are not the most classic use case, but I think usage beyong ASP.NET Core might be a thing to consider. The ASP.NET Core 2.1 future solution you mentioned would be based on ASP.NET Core and would not improve our UWP situation.

Thanks for any help or ideas.

**Comment by alhardy** [comment]
https://github.com/AppMetrics/Health/issues/9

**Comment by alhardy** [comment]
health checks deprecated due to Microsoft implementation
