### ISSUE TITLE
AspnetCore2.VersionedApi.QuickStart appsettings.Development.json is empty causing error

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [AppMetrics/Samples.V2#4]
Hello, there is a completely empty appsettings.Development.json in this project which means the first time anyone tries the sample they get an exception (below).
The solution is to change the appsettings.Development.json and put a set of empty braces in it:

`{}`

Error:

> Exception has occurred: CLR/System.FormatException
> An unhandled exception of type 'System.FormatException' occurred in Microsoft.Extensions.Configuration.FileExtensions.dll: 'Could not parse the JSON file. Error on line number '0': ''.'
>  Inner exceptions found, see $exception in variables window for more details.
>  Innermost exception 	 Newtonsoft.Json.JsonReaderException : Error reading JObject from JsonReader. Path '', line 0, position 0.
>    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)

**Comment by alhardy** [comment]
Fixed in latest
