### ISSUE TITLE
API version does not get injected into metrics

### ISSUE THREAD

**Issue by bardagadvergur** [AppMetrics/Samples.V2#5]
The AspNetCore2.VersionedApi project does not output the version correctly. The metrics-text endpoint displays this:

TIMESTAMP: 636880051673340380
MEASUREMENT: [Application.HttpRequests] Transactions Per Endpoint
TAGS:
                  route = GET api/v{version:apiversion}/values

**Comment by alhardy** [comment]
Fixed in latest
