### ISSUE TITLE
incorrect links to samples

### ISSUE THREAD

**Issue by constructor-igor** [AppMetrics/Samples.V2#6]
sample of incorrect link:

https://www.app-metrics.io/samples/health-code/

![image](https://user-images.githubusercontent.com/1849690/70239579-37523100-1774-11ea-93b0-ba9c2372360b.png)

go to https://github.com/AppMetrics/Samples.V2/tree/master/Net452.Health.Console.QuickStart

https://github.com/AppMetrics/Samples.V2/issues
![image](https://user-images.githubusercontent.com/1849690/70239605-4638e380-1774-11ea-91bc-58aaeff10c84.png)

**Comment by alhardy** [comment]
Health as been deprecated due to MS implementation
