### ISSUE TITLE
Apdex score always 1 on your sample project.

### ISSUE THREAD

**Issue by gulsenbi** [AppMetrics/Samples.V2#8]
I tried to add Apdex score calculation to my project the relaised that score never change. 
Look at your sample project which name is "AspNetCore2.Api.QuickStart" and its Apdex score never change too.
Result is always 1.

```
--------------------------------------------------------------
TIMESTAMP: 637291997050522649
MEASUREMENT: [Application.HttpRequests] Apdex
TAGS:
                 server = THB-DEV-131
                    app = MetricsSandboxMvc
                    env = configoverride
                  mtype = apdex
                   unit = result
FIELDS:
                samples = 43
                  score = 1
              satisfied = 4
             tolerating = 8
            frustrating = 31
```

Can you help me with this issue? 
Thanks,

**Comment by alhardy** [comment]
Thanks for raising, looks like a new bug

**Comment by gulsenbi** [comment]
Looks like an interesting bug there. If your sample request count below than 100, score never change but after 100 request score changed correctly. 
Hope this help to you.
Thanks
